### ISSUE TITLE
no config

### ISSUE THREAD

**Issue by lyhkeke** [oliverweissl/NeuralDecoderToric3D#1]
There is no config file when recopiing the code
@hydra.main(config_path="config", config_name="3d", version_base="1.2"

**Comment by oliverweissl** [comment]
Hello @lyhkeke ,
I will update the git soon with the config we used. 
However, you can remove the hydra part and simply find another way to pass the args.

Also i made better comments in the experiment file so its easier to understand.

If you are using this for a research project do you need our paper? Its not published anywhere but i can upload it to Arxive if you need.

**Comment by lyhkeke** [comment]
thans ，If you can upload the hydra config file. i'm interested in this project， looking forward to see your paper on Arxiv

**Comment by oliverweissl** [comment]
the configs are now on the main branch, but keep in mind the API details for W&B are empty so for it to work you either have to put yours there or simply remove the W&B functionality.

I will edit the paper a bit an soon post a link.

**Comment by oliverweissl** [comment]
i updated the readme with the arxiv submission.
If you have any feedback let me know, im looking to improve this :)
